import { describe, expect, it } from "vitest";
import {
  applyAttachmentAnalysis,
  isAttachmentAnalyzable,
} from "../src/agent/fileAnalysis";
import { Attachment } from "../src/shared/protocol";

describe("file analysis attachments", () => {
  it("treats images and binary files as analyzable, but leaves text alone", () => {
    expect(
      isAttachmentAnalyzable({
        path: "diagram.png",
        content: "[Image: diagram.png]",
        imageUrl: "data:image/png;base64,AAAA",
        mimeType: "image/png",
      })
    ).toBe(true);

    expect(
      isAttachmentAnalyzable({
        path: "spec.pdf",
        content: "[File: spec.pdf]",
        dataBase64: "AAAA",
        mimeType: "application/pdf",
      })
    ).toBe(true);

    expect(isAttachmentAnalyzable({ path: "README.md", content: "# Hi" })).toBe(false);
  });

  it("replaces analyzed attachments with markdown summaries for the main model", () => {
    const attachment: Attachment = {
      path: "spec.pdf",
      content: "[File: spec.pdf]",
      dataBase64: "AAAA",
      mimeType: "application/pdf",
    };

    expect(applyAttachmentAnalysis(attachment, "A short extracted summary.")).toEqual({
      path: "spec.pdf",
      content:
        "File analysis generated by the configured file model.\n\nA short extracted summary.",
      mimeType: "application/pdf",
    });
  });
});
