import { generateText, type LanguageModel, type ModelMessage } from "ai";
import * as path from "path";
import { Attachment } from "../shared/protocol";

export interface FileAnalysisSettings {
  enabled: boolean;
  provider: string;
  model: string;
  baseUrl: string;
  hasApiKey: boolean;
}

export interface FileAnalysisModel {
  model: LanguageModel;
  providerId: string;
  modelId: string;
}

export function isAttachmentAnalyzable(attachment: Attachment): boolean {
  if (attachment.imageUrl) {
    return true;
  }
  if (!attachment.dataBase64 || !attachment.mimeType) {
    return false;
  }
  return !attachment.mimeType.startsWith("text/");
}

export function applyAttachmentAnalysis(
  attachment: Attachment,
  analysis: string
): Attachment {
  return {
    path: attachment.path,
    content: `File analysis generated by the configured file model.\n\n${analysis.trim()}`,
    mimeType: attachment.mimeType,
  };
}

export async function analyzeAttachment(
  attachment: Attachment,
  fileModel: FileAnalysisModel,
  signal: AbortSignal
): Promise<Attachment> {
  if (!isAttachmentAnalyzable(attachment)) {
    return attachment;
  }

  const content: Array<Record<string, unknown>> = [
    {
      type: "text",
      text:
        "Read and analyze this attached file for a coding assistant. " +
        "Return concise markdown with: file type, visible/extracted text, key facts, " +
        "tables or structure if present, and any uncertainty. Do not invent details.",
    },
  ];

  if (attachment.imageUrl) {
    content.push({
      type: "image",
      image: attachment.imageUrl,
      mediaType: attachment.mimeType,
    });
  } else if (attachment.dataBase64 && attachment.mimeType) {
    content.push({
      type: "file",
      data: Buffer.from(attachment.dataBase64, "base64"),
      filename: path.basename(attachment.path),
      mediaType: attachment.mimeType,
    });
  }

  const result = await generateText({
    model: fileModel.model,
    abortSignal: signal,
    messages: [
      {
        role: "system",
        content:
          "You are a document and image analysis model. Extract only what can be observed " +
          "from the supplied file and format the result for another model to use as context.",
      },
      { role: "user", content } as unknown as ModelMessage,
    ],
  });

  return applyAttachmentAnalysis(
    attachment,
    `Source: ${attachment.path}\nModel: ${fileModel.providerId}/${fileModel.modelId}\n\n${result.text}`
  );
}

export async function analyzeAttachments(
  attachments: Attachment[],
  fileModel: FileAnalysisModel,
  signal: AbortSignal,
  onProgress?: (message: string) => void
): Promise<Attachment[]> {
  const analyzed: Attachment[] = [];
  for (const attachment of attachments) {
    if (!isAttachmentAnalyzable(attachment)) {
      analyzed.push(attachment);
      continue;
    }
    onProgress?.(`Analyzing ${attachment.path} with ${fileModel.providerId}/${fileModel.modelId}...`);
    analyzed.push(await analyzeAttachment(attachment, fileModel, signal));
  }
  return analyzed;
}
