import * as fs from "fs";
import * as os from "os";
import * as path from "path";
import { runTests } from "@vscode/test-electron";

async function main() {
  const extensionDevelopmentPath = path.resolve(__dirname, "../..");
  const extensionTestsPath = path.resolve(__dirname, "suite", "extension.test.js");
  const workspacePath = fs.mkdtempSync(path.join(os.tmpdir(), "ai-agent-chat-e2e-"));

  fs.writeFileSync(
    path.join(workspacePath, "fixture.txt"),
    "fixture content from VS Code extension host\n",
    "utf8"
  );

  const mockSteps = [
    {
      type: "tool",
      id: "call-read-fixture",
      name: "read_file",
      args: { path: "fixture.txt" },
    },
    {
      type: "tool",
      id: "call-write-generated",
      name: "write_file",
      args: { path: "generated.txt", content: "generated by e2e\n" },
    },
    {
      type: "text",
      text: "The fixture was read successfully.",
    },
  ];

  await runTests({
    extensionDevelopmentPath,
    extensionTestsPath,
    extensionTestsEnv: {
      AI_AGENT_CHAT_E2E_MOCK_STEPS: JSON.stringify(mockSteps),
    },
    launchArgs: [workspacePath, "--disable-workspace-trust"],
  });
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
